### ISSUE TITLE
unexpected token 'export' while using ts-node.

### ISSUE THREAD

**Issue by vansham-gortnm** [dankogai/js-combinatorics#80]
I installed the package using the command `npm i <repo_url>`. 

And then I imported it using the statement `import { Permutations } from 'js-combinatorics`. 

But when we run it it gives the error 

`unexpected token 'const' in the file 'combinatorics.js' `.

And I wonder why the file 'combinatorics.ts' is not included in the package

**Comment by dankogai** [comment]
`combinatorics.ts` is not included in the npm package because  `combinatorics.d.ts` is included. see

* https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

And I do not understand `unexpected token 'const' in the file 'combinatorics.js'` at all.  Do you mean `unexpected token 'export' in the file 'combinatorics.js'` as the title of this issue says?  Then chances are your environment does not support ES module.  See

* https://github.com/dankogai/js-combinatorics#commonjs-nodejs

**Comment by electic** [comment]
I am running into the same problem as well. Installing ts-combinatorics as well, solved the issue. But I feel like that might not be the right answer.

**Comment by D-Nice1** [comment]
There is a version of this for typescript specifically that may help you, I found it since I cannot use this library directly anymore since v1 and ythe elimination of permutationCombination and no response for the issue - even after I converted my project to be ts compatible I was getting this same error 'unexpected token 'export' - checkout ts-combinatorics - created specifically since there are issues with ts.
